### ISSUE TITLE
Сontainer does not start

### ISSUE THREAD

**Issue by RasputinGrig** [vaerh/docker-routeros#37]
I see this in the logs:

> udhcpd: started, v1.36.1
udhcpd: max_leases=235 is too big, setting to 1
udhcpd: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
Device "eth1" does not exist.
Cannot find device "eth1"
Cannot find device "eth1"
Device "eth2" does not exist.
Cannot find device "eth2"
Cannot find device "eth2"
Device "eth3" does not exist.
Cannot find device "eth3"
Cannot find device "eth3"
Device "eth4" does not exist.
Cannot find device "eth4"
Cannot find device "eth4"
Device "eth5" does not exist.
Cannot find device "eth5"
Cannot find device "eth5"
Device "eth6" does not exist.
Cannot find device "eth6"
Cannot find device "eth6"
Device "eth7" does not exist.
Cannot find device "eth7"
Cannot find device "eth7"
qemu-system-x86_64: -nic tap,id=qemu1,mac=54:05:AB:CD:12:31,script=/routeros/qemu-ifup,downscript=/routeros/qemu-ifdown: could not open /dev/net/tun: No such device

**Comment by vaerh** [comment]
Please check [this](https://github.com/EvilFreelancer/docker-routeros/issues/13#issuecomment-944082209)
